// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreMaster.Infrastructure.Persistence.Context;

#nullable disable

namespace StoreMaster.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240630235835_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_produto");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("categoria_produto", (string)null);
                });

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.StockConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<decimal>("MinimumStockAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantidade_minima_estoque");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("configuracao_estoque", (string)null);
                });

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<int>("StockMovementType")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimento_estoque");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("movimento_estoque", (string)null);
                });

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.Product", b =>
                {
                    b.HasOne("StoreMaster.Infrastructure.Persistence.Entry.ProductCategory", "ProductCategory")
                        .WithMany("ListProduct")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_produto_categoria_produto_id_categoria_produto");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("StoreMaster.Infrastructure.Persistence.Entry.ProductCategory", b =>
                {
                    b.Navigation("ListProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
